### ISSUE TITLE
Could you upload the processed data file as well? Please

### ISSUE THREAD

**Issue by JohnnyQAQ** [Brophy-E/ECG_GAN_MBD#3]
Hi,I am a college student from China.
I want to reproduce it，But I lack the experimental data(mitbih_train.csv and mitbih_test.csv),I hope you can share them,thank you so much!

**Comment by gib4** [comment]
Hi @JohnnyQAQ,
I am almost sure that they are using the pre-processed data set from Kaggle: https://www.kaggle.com/shayanfazeli/heartbeat. The data set is divided into mitbih_train.csv  and mitbih_test.csv. I'm using "almost", because when using the model to generate the ECG signals in the same conditions on Colab, I'm running out of memory.

I would be glad if someone could clarify the out of memory issue.

**Comment by Brophy-E** [comment]
[Here is a link](https://drive.google.com/drive/folders/1AsgzVmsOWAQEHPQu_YqGfF3RvkhOTV39?usp=sharing) to a shared Google Drive folder with an example of the data we used for [this other paper](https://dl.acm.org/doi/abs/10.1145/3340531.3418509).  

Please Note: the data is formatted as multichannel ECG with a shape of [109246,187,2]. If you are having an OOM issue just use a sub set of this data.  Also for the code in this repo just select one of the available leads. 

Say you want 50K samples then your array shape should be [50000, 187, 1]

Cheers
